void Draw_UserCheatsMenu_Ani(struct save_entry * games, int games_len);
void Draw_UserCheatsMenu(struct save_entry * games, int games_len, int menuSel, u8 alpha);
void Draw_CheatsMenu_Selection_Ani();
void Draw_CheatsMenu_Selection(int menuSel, u32 rgba);
void Draw_CheatsMenu_View_Ani_Exit(void);
void Draw_CheatsMenu_View_Ani(void);
void Draw_CheatsMenu_View(void);
void Draw_CheatsMenu_Options_Ani_Exit(void);
void Draw_CheatsMenu_Options_Ani(void);
void Draw_CheatsMenu_Options(void);