name: Build package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout dbglogger
      uses: actions/checkout@v4
      with:
        repository: bucanero/dbglogger
        path: dbglogger

    - name: Checkout apollo-lib
      uses: actions/checkout@v4
      with:
        repository: bucanero/apollo-lib
        path: apollo-lib

    - name: Checkout libxmp-lite-ps4
      uses: actions/checkout@v4
      with:
        repository: bucanero/libxmp-lite-ps4
        path: libxmp-lite-ps4

    - name: Checkout mini18n
      uses: actions/checkout@v4
      with:
        repository: bucanero/mini18n
        path: mini18n

    - name: Set env vars
      id: slug
      run: |
        echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
        sudo apt install python2.7

      # using pre-compiled sdk
    - name: Download PSL1GHT Toolchain
      run: |
        curl -sL https://github.com/bucanero/ps3toolchain/releases/download/ubuntu-latest-fad3b5fb/ps3dev-ubuntu-latest-2020-08-31.tar.gz | tar xvz -C ./
        curl -sL https://github.com/ps3dev/PSL1GHT/raw/master/ppu/include/sysutil/sysutil.h -o ps3dev/ppu/include/sysutil/sysutil.h
        echo "PS3DEV=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV
        echo "PSL1GHT=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV

    - name: Install mbedTLS
      run: |
        curl -sL https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-2.28.10/mbedtls-2.28.10.tar.bz2 | tar xvj -C ./
        curl -sL https://github.com/bucanero/ps3libraries/raw/refs/heads/master/patches/mbedtls-2.28.10.patch -o mbedtls-2.28.10.patch
        cd mbedtls-2.28.10
        patch -p1 < ../mbedtls-2.28.10.patch
        cd library
        chmod +x ps3-build.sh
        ./ps3-build.sh
        cp lib*.a $PS3DEV/portlibs/ppu/lib/
        cp -R ../include/mbedtls $PS3DEV/portlibs/ppu/include/

    - name: Install cURL
      run: |
        curl -sL https://gist.githubusercontent.com/bucanero/c0b3e143657df54f28e2027abca13c71/raw/1670eb108f1c6e00b7bc689fc4ece873ee2b665f/curl-ps3-build.sh -o curl-ps3-build.sh
        chmod +x curl-ps3-build.sh
        ./curl-ps3-build.sh

    - name: Install dbglogger
      working-directory: dbglogger
      run: |
        make install

    - name: Install apollo-lib
      working-directory: apollo-lib
      run: |
        sed -i '40s/.*/MACHDEP := -DBIGENDIAN -D_USE_MBEDTLS/' Makefile
        make install

    - name: Install libxmp-lite
      working-directory: libxmp-lite-ps4
      run: |
        make -f Makefile.ps3 install

    - name: Install mini18n
      working-directory: mini18n
      run: |
        make install

    - name: Build Apollo App Package
      run: |
        make createzip
        make pkg

    - name: Push package artifact
      uses: actions/upload-artifact@v4
      with:
        name: apollo-ps3-build_${{ env.sha_name }}
        path: apollo-ps3.pkg
        if-no-files-found: error
